apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: 3000
      targetPort: 3000