apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: product
  namespace: ecommerce
  labels:
    app.kubernetes.io/part-of: ecommerce
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: product
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order
  namespace: ecommerce
  labels:
    app.kubernetes.io/part-of: ecommerce
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway
  namespace: ecommerce
  labels:
    app.kubernetes.io/part-of: ecommerce
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway